FROM node:20-alpine

RUN addgroup -g 1001 -S nodejs && \
    adduser -S nodejs -u 1001

USER nodejs

WORKDIR /app

COPY --chown=nodejs:nodejs package.json yarn.lock* ./

RUN yarn install

COPY --chown=nodejs:nodejs . .

EXPOSE 4000

CMD ["yarn", "dev"]